# Generated by Django 4.1.2 on 2022-12-01 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('type', models.CharField(choices=[('lost', 'Потерял'), ('find', 'Нашел')], max_length=50)),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('documents', 'Документ'), ('keys', 'Ключи'), ('electronik', 'электроника'), ('animals', 'Животные'), ('jewelry', 'Драгоценности'), ('bags', 'Сумки'), ('phones', 'телефоны'), ('other', 'Другое')], max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=13)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('address', models.CharField(choices=[('Balykchy', 'Балыкчы'), ('Bishkek', 'Бишкек'), ('Kant', 'Кант'), ('Karakol', 'Каракол'), ('Naryn', 'Нарын'), ('Osh', 'Ош'), ('Talas', 'Талас'), ('Tokmok', 'Токмок')], max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=13, null=True)),
                ('date', models.DateField(verbose_name='Дата находки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='table.advert')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
