# Generated by Django 4.1.2 on 2022-12-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
