# Generated by Django 4.1.2 on 2022-12-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='type',
            field=models.CharField(choices=[('найдено', 'find'), ('потеряно', 'lost')], max_length=200),
        ),
    ]
